//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorBike
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Motorbike
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Horsepower { get; set; }
        public Nullable<int> Mileage { get; set; }
        public string Picture { get; set; }
    }
}
